// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/trophy-case/Cabinet.tsx": () => import("../components/mockups/trophy-case/Cabinet.tsx"),
  "./components/mockups/trophy-case/Current.tsx": () => import("../components/mockups/trophy-case/Current.tsx")
};
