// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/birthday-popup/Current.tsx": () => import("../components/mockups/birthday-popup/Current.tsx"),
  "./components/mockups/trophy-case/Cabinet.tsx": () => import("../components/mockups/trophy-case/Cabinet.tsx"),
  "./components/mockups/trophy-case/Current.tsx": () => import("../components/mockups/trophy-case/Current.tsx"),
  "./components/mockups/roster-home/AboutPage.tsx": () => import("../components/mockups/roster-home/AboutPage.tsx"),
  "./components/mockups/roster-home/Current.tsx": () => import("../components/mockups/roster-home/Current.tsx"),
  "./components/mockups/roster-home/FeaturesPage.tsx": () => import("../components/mockups/roster-home/FeaturesPage.tsx"),
  "./components/mockups/roster-home/PartnersPage.tsx": () => import("../components/mockups/roster-home/PartnersPage.tsx"),
  "./components/mockups/roster-home/PricingPage.tsx": () => import("../components/mockups/roster-home/PricingPage.tsx"),
  "./components/mockups/roster-home/RosterPageNav.tsx": () => import("../components/mockups/roster-home/RosterPageNav.tsx"),
  "./components/mockups/roster-home/ScrollStory.tsx": () => import("../components/mockups/roster-home/ScrollStory.tsx")
};
